name= input("enter your name")
age= input("enter your age")
gender= input ("enter you gender")
SSLC_MARK= input("enter your sslc mark")
HSC_MARK= input("enter your hsc mark")
print(name)
print("my age is",age)
print("my gender is",gender)
print("my sslc mark is",SSLC_MARK)
print(HSC_MARK)

