print("Father's name is 'DASARATHAN'")
print("Mother's name is 'THUNAISELVI'")
print("SSLC PASSSED OUT WITH '91%' 445 year '2014' ")
print("HSC PASSED OUT WITH '69%' 838 year '2016'")
print("BE CIVIL ENGINEERING WITH '7.05' CGPA year '2020'")
print("i am comming from 'ARUPPUKOTTAI'")
print("My strengthness is 'optimistic' and 'addaptablity'")
print("My weakness is hard working person but not in consistent manner")
print("my short term goal is to place in a reputed mnc as a juniour data analysist")
print("my long term goal is to place in Goldman Sacs as a seniour alalysist")
